# Book settings
title: Introduction to Topic Modeling and Text Classification
author: William Mattingly
logo: 'images/data_science_lab_logo.png'
execute:
  execute_notebooks: 'off'
parse:
  myst_extended_syntax: true
